let games = [
  {
    name: "Minecraft: Playstation 4 Edition",
    game_id: "93620",
    release: "Haven't looked",
    genre: "Shooter",
    platforms: "PS4",
    summary:
      "Data from IGDB has not been loaded.  The critically acclaimed Minecraft comes to PlayStation 4. Create your very own game world and explore, build and conquer.",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ur4.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/f0mtqk9zdqoulrf0nfzu.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/jf38rmtqfajincjbmlhk.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/ggo7l7nmnscwm2dxwxpm.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/u96la3yypflh3px1x4zc.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/f0mtqk9zdqoulrf0nfzu.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/plhsbped062flaoknbzt.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/diq3mxcap0gnbbgeqpwg.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/o5ibznm0jhxvumujptuv.jpg",
    ],
    video: "https://www.youtube.com/embed/1DhWXAiNgfQ",
  },
  {
    name: "Marvel's Spider Man",
    game_id: "19565",
    release: "7th September, 2018",
    genre: "Adventure",
    platforms: "PS4",
    summary: "Game based on the Spider Man movies with Peter Parker.",
    cover: "https://images.igdb.com/igdb/image/upload/t_original/co1r77.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khp.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khv.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khw.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khq.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khs.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6kht.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khu.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6khx.jpg",
    ],
    video: "https://www.youtube.com/embed/q4GdJVvdxss",
  },
  {
    name: "God of War",
    game_id: "19560",
    release: "20th April 2018",
    genre: "Adventure, Role-playing(RPG)",
    platforms: "PS4",
    summary: "An adventure games with Kratos and his son.",
    cover: "https://images.igdb.com/igdb/image/upload/t_original/co1tmu.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/mknszfnaifmhssbrmkpl.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/r7hpzsqic1bjwyzn1bnq.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/wunlbofh23trw0u67gms.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/s2zdtxopibrfjbxvpj5h.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/o4mg2wvhlcikaogvvzqe.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/gpt3d0gpue5mat4kkso6.jpg",
    ],
    video: "https://www.youtube.com/embed/rClXqZD2Xrs",
  },
  {
    name: "Death Stranding",
    game_id: "19564",
    release: "20th November 2019",
    genre: "Adventure, Role-playing(RPG)",
    platforms: "PS4",
    summary:
      "A really famous game with alot of big name actors and the likeness from that guy from Walking Dead.",
    cover: "https://images.igdb.com/igdb/image/upload/t_original/co1syk.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/mknszfnaifmhssbrmkpl.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/r7hpzsqic1bjwyzn1bnq.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/wunlbofh23trw0u67gms.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/s2zdtxopibrfjbxvpj5h.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/o4mg2wvhlcikaogvvzqe.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/gpt3d0gpue5mat4kkso6.jpg",
    ],
    video: "https://www.youtube.com/embed/tCI396HyhbQ",
  },
  {
    name: "Call of Duty",
    game_id: "83727",
    release: "25th October 2019",
    genre: "Shooter",
    platforms: "PS4",
    summary: "One of the ultimate shoot em up games.",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wkf.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/sc6qen.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/sc6qem.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/ar6dr.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/gxrqetgeesus7abzlxsu.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/bofvxbntojlvpwueihdg.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/yyynkripplx43svs9ifw.jpg",
    ],
    video: "https://www.youtube.com/embed/3pyfKYwlGhQ",
  },
  {
    name: "Uncharted",
    game_id: "7331",
    release: "Haven't looked",
    genre: "Fantasy",
    platforms: "PS4",
    summary: "Data from IGDB has not been loaded.",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.jpg",
    screenshots: [
      "https://images.igdb.com/igdb/image/upload/t_original/fn1wbuvikoacxt4zvfxl.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/b41umzxjcehm8fozl3gf.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/tqt0sxjytiovh3g96cl0.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/qwytrspu8brvow9x9y15.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/rtu8k7vm5x4mw5hilh2z.jpg",
      "https://images.igdb.com/igdb/image/upload/t_original/yyynkripplx43svs9ifw.jpg",
    ],
    video: "https://www.youtube.com/embed/3pyfKYwlGhQ",
  },
];



export default games;
